package com.lxd.pojo;

import java.util.Date;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_category.id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_category.parent_id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_category.name
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_category.stauts
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Boolean stauts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_category.sort_order
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_category.create_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_category.update_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_category
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Category(Integer id, Integer parentId, String name, Boolean stauts, Integer sortOrder, Date createTime, Date updateTime) {
        this.id = id;
        this.parentId = parentId;
        this.name = name;
        this.stauts = stauts;
        this.sortOrder = sortOrder;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_category
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Category() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_category.id
     *
     * @return the value of ssm_category.id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_category.id
     *
     * @param id the value for ssm_category.id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_category.parent_id
     *
     * @return the value of ssm_category.parent_id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_category.parent_id
     *
     * @param parentId the value for ssm_category.parent_id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_category.name
     *
     * @return the value of ssm_category.name
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_category.name
     *
     * @param name the value for ssm_category.name
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_category.stauts
     *
     * @return the value of ssm_category.stauts
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Boolean getStauts() {
        return stauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_category.stauts
     *
     * @param stauts the value for ssm_category.stauts
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setStauts(Boolean stauts) {
        this.stauts = stauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_category.sort_order
     *
     * @return the value of ssm_category.sort_order
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_category.sort_order
     *
     * @param sortOrder the value for ssm_category.sort_order
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_category.create_time
     *
     * @return the value of ssm_category.create_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_category.create_time
     *
     * @param createTime the value for ssm_category.create_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_category.update_time
     *
     * @return the value of ssm_category.update_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_category.update_time
     *
     * @param updateTime the value for ssm_category.update_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}