package com.lxd.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.order_no
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Long orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.user_id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.shipping_id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer shippingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.payment
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private BigDecimal payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.payment_type
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer paymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.postage
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer postage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.status
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.pay_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.send_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.close_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Date closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.create_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_order.update_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_order
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Order(Integer id, Long orderNo, Integer userId, Integer shippingId, BigDecimal payment, Integer paymentType, Integer postage, Integer status, Date payTime, Date sendTime, Date closeTime, Date createTime, Date updateTime) {
        this.id = id;
        this.orderNo = orderNo;
        this.userId = userId;
        this.shippingId = shippingId;
        this.payment = payment;
        this.paymentType = paymentType;
        this.postage = postage;
        this.status = status;
        this.payTime = payTime;
        this.sendTime = sendTime;
        this.closeTime = closeTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_order
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Order() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.id
     *
     * @return the value of ssm_order.id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.id
     *
     * @param id the value for ssm_order.id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.order_no
     *
     * @return the value of ssm_order.order_no
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.order_no
     *
     * @param orderNo the value for ssm_order.order_no
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.user_id
     *
     * @return the value of ssm_order.user_id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.user_id
     *
     * @param userId the value for ssm_order.user_id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.shipping_id
     *
     * @return the value of ssm_order.shipping_id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.shipping_id
     *
     * @param shippingId the value for ssm_order.shipping_id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setShippingId(Integer shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.payment
     *
     * @return the value of ssm_order.payment
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.payment
     *
     * @param payment the value for ssm_order.payment
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.payment_type
     *
     * @return the value of ssm_order.payment_type
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.payment_type
     *
     * @param paymentType the value for ssm_order.payment_type
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.postage
     *
     * @return the value of ssm_order.postage
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.postage
     *
     * @param postage the value for ssm_order.postage
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setPostage(Integer postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.status
     *
     * @return the value of ssm_order.status
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.status
     *
     * @param status the value for ssm_order.status
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.pay_time
     *
     * @return the value of ssm_order.pay_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.pay_time
     *
     * @param payTime the value for ssm_order.pay_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.send_time
     *
     * @return the value of ssm_order.send_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.send_time
     *
     * @param sendTime the value for ssm_order.send_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.close_time
     *
     * @return the value of ssm_order.close_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.close_time
     *
     * @param closeTime the value for ssm_order.close_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.create_time
     *
     * @return the value of ssm_order.create_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.create_time
     *
     * @param createTime the value for ssm_order.create_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_order.update_time
     *
     * @return the value of ssm_order.update_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_order.update_time
     *
     * @param updateTime the value for ssm_order.update_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}