package com.lxd.pojo;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user. uername
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private String uername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.passwrod
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private String passwrod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.email
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.phone
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.question
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.answer
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.role
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.create_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssm_user.update_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_user
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public User(Integer id, String uername, String passwrod, String email, String phone, String question, String answer, Integer role, Date createTime, Date updateTime) {
        this.id = id;
        this.uername = uername;
        this.passwrod = passwrod;
        this.email = email;
        this.phone = phone;
        this.question = question;
        this.answer = answer;
        this.role = role;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssm_user
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.id
     *
     * @return the value of ssm_user.id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.id
     *
     * @param id the value for ssm_user.id
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user. uername
     *
     * @return the value of ssm_user. uername
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public String getUername() {
        return uername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user. uername
     *
     * @param uername the value for ssm_user. uername
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setUername(String uername) {
        this.uername = uername == null ? null : uername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.passwrod
     *
     * @return the value of ssm_user.passwrod
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public String getPasswrod() {
        return passwrod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.passwrod
     *
     * @param passwrod the value for ssm_user.passwrod
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setPasswrod(String passwrod) {
        this.passwrod = passwrod == null ? null : passwrod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.email
     *
     * @return the value of ssm_user.email
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.email
     *
     * @param email the value for ssm_user.email
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.phone
     *
     * @return the value of ssm_user.phone
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.phone
     *
     * @param phone the value for ssm_user.phone
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.question
     *
     * @return the value of ssm_user.question
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.question
     *
     * @param question the value for ssm_user.question
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.answer
     *
     * @return the value of ssm_user.answer
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.answer
     *
     * @param answer the value for ssm_user.answer
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.role
     *
     * @return the value of ssm_user.role
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.role
     *
     * @param role the value for ssm_user.role
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.create_time
     *
     * @return the value of ssm_user.create_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.create_time
     *
     * @param createTime the value for ssm_user.create_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssm_user.update_time
     *
     * @return the value of ssm_user.update_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssm_user.update_time
     *
     * @param updateTime the value for ssm_user.update_time
     *
     * @mbg.generated Sun Sep 16 09:43:18 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}